#!/bin/bash

pip install -r requirements.txt

JOURNAL_FOLDER="YOUR JOURNAL FOLDER"
SCREENSHOT_FOLDER="THE ELITE DANGEROUS SCREENSHOT FOLDER"

python EDScreenshot.py "$JOURNAL_FOLDER" "$SCREENSHOT_FOLDER"